apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "php-poc.fullname" . }}
  labels:
    {{- include "php-poc.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "php-poc.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "php-poc.fullname" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: php-poc-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: environment
              mountPath: /etc/environment
              subPath: environment
      volumes:
        - name: environment
          configMap:
            name: {{ include "php-poc.fullname" . }}-env
